-- Elega: initial schema draft (Step 2 blueprint).
--
-- Status: DRAFT for review. At M0 this file is split into Drizzle-managed SQL
-- migrations under apps/api/db/migrations; it is not executed by any app yet.
-- Verified by applying it to an empty PostgreSQL 16 database (see docs/database.md).
--
-- Conventions (docs/database.md, ADR-009):
--   * Primary keys are UUIDv7, generated by the application; uuid_generate_v7()
--     below is the database-side fallback for defaults and manual inserts.
--   * Enumerations are text + CHECK constraints (cheaper to evolve than PG enums).
--   * Every table has created_at / updated_at (timestamptz, UTC).
--   * User content is soft-deleted (deleted_at); a retention job hard-deletes it.
--   * Hot lists use partial indexes WHERE deleted_at IS NULL.

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- RFC 9562 UUIDv7: 48-bit unix ms timestamp, version 7, variant 10, random rest.
CREATE OR REPLACE FUNCTION uuid_generate_v7() RETURNS uuid
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
  ts_ms bigint := floor(extract(epoch FROM clock_timestamp()) * 1000);
  bytes bytea := gen_random_bytes_compat(16);
BEGIN
  bytes := set_byte(bytes, 0, ((ts_ms >> 40) & 255)::int);
  bytes := set_byte(bytes, 1, ((ts_ms >> 32) & 255)::int);
  bytes := set_byte(bytes, 2, ((ts_ms >> 24) & 255)::int);
  bytes := set_byte(bytes, 3, ((ts_ms >> 16) & 255)::int);
  bytes := set_byte(bytes, 4, ((ts_ms >> 8) & 255)::int);
  bytes := set_byte(bytes, 5, (ts_ms & 255)::int);
  bytes := set_byte(bytes, 6, (get_byte(bytes, 6) & 15) | 112);  -- version 7
  bytes := set_byte(bytes, 8, (get_byte(bytes, 8) & 63) | 128);  -- variant 10
  RETURN encode(bytes, 'hex')::uuid;
END $$;

-- 16 random bytes without requiring pgcrypto.
CREATE OR REPLACE FUNCTION gen_random_bytes_compat(n int) RETURNS bytea
LANGUAGE sql VOLATILE AS $$
  SELECT decode(substr(replace(gen_random_uuid()::text, '-', '') ||
                       replace(gen_random_uuid()::text, '-', ''), 1, n * 2), 'hex')
$$;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- Search normalisation: lower-case, strip accents, treat ё as е.
CREATE OR REPLACE FUNCTION search_normalize(input text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT translate(lower(public.unaccent('public.unaccent'::regdictionary, coalesce(input, ''))), 'ё', 'е')
$$;

-- ---------------------------------------------------------------------------
-- 7.6 Media (first: many tables reference it)
-- ---------------------------------------------------------------------------

CREATE TABLE media (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  owner_id          uuid NOT NULL,  -- FK added after users
  kind              text NOT NULL CHECK (kind IN ('image', 'video', 'audio', 'file')),
  storage_key       text NOT NULL UNIQUE,
  original_filename text,
  mime_type         text,           -- verified by magic bytes in media.process
  size_bytes        bigint CHECK (size_bytes >= 0),
  width             int CHECK (width > 0),
  height            int CHECK (height > 0),
  duration_ms       int CHECK (duration_ms >= 0),
  blurhash          text,
  status            text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'processing', 'ready', 'rejected')),
  variants_json     jsonb NOT NULL DEFAULT '{}'::jsonb,
  checksum_sha256   bytea,
  moderation_status text NOT NULL DEFAULT 'unreviewed'
                    CHECK (moderation_status IN ('unreviewed', 'approved', 'needs_review', 'rejected')),
  attached_at       timestamptz,    -- set when referenced; orphans cleaned after 24h
  deleted_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX media_owner_idx ON media (owner_id, created_at DESC);
CREATE INDEX media_orphans_idx ON media (created_at) WHERE attached_at IS NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- 7.1 Auth and users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  email                 citext NOT NULL UNIQUE,
  email_verified_at     timestamptz,
  password_hash         text,  -- argon2id; NULL for OAuth-only accounts
  username              citext NOT NULL UNIQUE
                        CHECK (username::text ~ '^[a-z0-9._]{3,30}$' AND username::text !~ '\.\.'),
  display_name          text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 64),
  status                text NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'suspended', 'pending_deletion', 'banned')),
  role                  text NOT NULL DEFAULT 'user'
                        CHECK (role IN ('user', 'moderator', 'analyst', 'admin')),
  trust_level           smallint NOT NULL DEFAULT 0 CHECK (trust_level BETWEEN 0 AND 4),
  locale                text NOT NULL DEFAULT 'ru' CHECK (locale IN ('ru', 'en')),
  timezone              text NOT NULL DEFAULT 'Europe/Moscow',
  birthdate             date NOT NULL,
  -- is_minor = adult_from > current_date; stored generated column keeps it indexable.
  adult_from            date GENERATED ALWAYS AS ((birthdate + interval '18 years')::date) STORED,
  phone_e164            text CHECK (phone_e164 ~ '^\+[1-9][0-9]{6,14}$'),
  invited_by_code_id    uuid,
  last_seen_at          timestamptz,
  deletion_scheduled_at timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CHECK (birthdate <= (created_at - interval '14 years')::date)
);
CREATE INDEX users_display_name_trgm ON users USING gin (search_normalize(display_name) gin_trgm_ops);
CREATE INDEX users_username_trgm ON users USING gin ((username::text) gin_trgm_ops);
CREATE INDEX users_pending_deletion_idx ON users (deletion_scheduled_at) WHERE status = 'pending_deletion';

ALTER TABLE media ADD CONSTRAINT media_owner_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE user_profiles (
  user_id                 uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  bio                     text CHECK (char_length(bio) <= 500),
  city                    text,
  country                 text,
  workplace               text,
  education               text,
  website                 text,
  pronouns                text,
  relationship_status     text,
  avatar_media_id         uuid REFERENCES media (id) ON DELETE SET NULL,
  cover_media_id          uuid REFERENCES media (id) ON DELETE SET NULL,
  -- {"city": "friends", "birthday": "only_me", ...}; values from the audience set in 9.2
  profile_visibility_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  links_json              jsonb NOT NULL DEFAULT '[]'::jsonb,
  pinned_post_id          uuid,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_settings (
  user_id                      uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  theme                        text NOT NULL DEFAULT 'system' CHECK (theme IN ('light', 'dark', 'system')),
  font_scale                   numeric(3, 2) NOT NULL DEFAULT 1.00 CHECK (font_scale BETWEEN 1.00 AND 2.00),
  feed_mode                    text NOT NULL DEFAULT 'chronological' CHECK (feed_mode IN ('chronological', 'for_you')),
  who_can_message              text NOT NULL DEFAULT 'everyone' CHECK (who_can_message IN ('everyone', 'friends', 'nobody')),
  who_can_send_friend_requests text NOT NULL DEFAULT 'everyone'
                               CHECK (who_can_send_friend_requests IN ('everyone', 'friends_of_friends', 'nobody')),
  who_can_see_online_status    text NOT NULL DEFAULT 'friends' CHECK (who_can_see_online_status IN ('everyone', 'friends', 'nobody')),
  who_can_mention              text NOT NULL DEFAULT 'everyone' CHECK (who_can_mention IN ('everyone', 'friends', 'nobody')),
  allow_followers              boolean NOT NULL DEFAULT true,
  read_receipts_enabled        boolean NOT NULL DEFAULT true,
  default_post_audience        text NOT NULL DEFAULT 'friends'
                               CHECK (default_post_audience IN ('public', 'friends', 'close_friends', 'only_me')),
  search_engine_indexing       boolean NOT NULL DEFAULT false,
  discoverable_by_email        boolean NOT NULL DEFAULT false,
  data_saver                   boolean NOT NULL DEFAULT false,
  notification_preferences_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  quiet_hours_json             jsonb,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE auth_credentials (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id          uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider         text NOT NULL CHECK (provider IN ('password', 'vk', 'yandex', 'google')),
  provider_user_id text NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_user_id),
  UNIQUE (user_id, provider)
);

CREATE TABLE sessions (
  id                 uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id            uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  family_id          uuid NOT NULL,  -- all rotations of one login; revoked together on reuse
  refresh_token_hash bytea NOT NULL UNIQUE,  -- SHA-256 of a 256-bit random token
  device_name        text,
  user_agent         text,
  ip_hash            bytea,
  coarse_location    text,
  remember_device    boolean NOT NULL DEFAULT false,
  last_used_at       timestamptz NOT NULL DEFAULT now(),
  expires_at         timestamptz NOT NULL,
  revoked_at         timestamptz,
  rotated_from_id    uuid REFERENCES sessions (id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_family_idx ON sessions (family_id);

CREATE TABLE email_tokens (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type       text NOT NULL CHECK (type IN ('verify_email', 'reset_password', 'change_email')),
  token_hash bytea NOT NULL UNIQUE,
  new_email  citext,  -- for change_email only
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((type = 'change_email') = (new_email IS NOT NULL))
);
CREATE INDEX email_tokens_user_idx ON email_tokens (user_id, type);

CREATE TABLE totp_secrets (
  user_id              uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  secret_encrypted     bytea NOT NULL,  -- AES-256-GCM, key from env/KMS
  key_version          smallint NOT NULL,
  confirmed_at         timestamptz,
  recovery_codes_hash  bytea[] NOT NULL DEFAULT '{}',
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE login_attempts (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  identifier_hash bytea NOT NULL,
  ip_hash         bytea NOT NULL,
  success         boolean NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX login_attempts_identifier_idx ON login_attempts (identifier_hash, created_at DESC);
CREATE INDEX login_attempts_ip_idx ON login_attempts (ip_hash, created_at DESC);

-- Staged rollout (37.3): invite-only registration until open beta.
CREATE TABLE invite_codes (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  code_hash   bytea NOT NULL UNIQUE,
  created_by  uuid REFERENCES users (id) ON DELETE SET NULL,
  max_uses    int NOT NULL DEFAULT 1 CHECK (max_uses > 0),
  used_count  int NOT NULL DEFAULT 0 CHECK (used_count >= 0),
  expires_at  timestamptz,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CHECK (used_count <= max_uses)
);
ALTER TABLE users ADD CONSTRAINT users_invite_fk FOREIGN KEY (invited_by_code_id) REFERENCES invite_codes (id) ON DELETE SET NULL;

CREATE TABLE username_history (
  username      citext PRIMARY KEY,  -- old name redirects for 30 days (9.5)
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  released_at   timestamptz NOT NULL DEFAULT now(),
  redirect_until timestamptz NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 7.2 Relationships
-- ---------------------------------------------------------------------------

CREATE TABLE friendships (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_a_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  user_b_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status       text NOT NULL CHECK (status IN ('pending', 'accepted')),
  requested_by uuid NOT NULL,
  accepted_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CHECK (user_a_id < user_b_id),
  CHECK (requested_by IN (user_a_id, user_b_id)),
  CHECK ((status = 'accepted') = (accepted_at IS NOT NULL)),
  UNIQUE (user_a_id, user_b_id)
);
CREATE INDEX friendships_a_idx ON friendships (user_a_id, status);
CREATE INDEX friendships_b_idx ON friendships (user_b_id, status);

CREATE TABLE follows (
  follower_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  followee_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (follower_id, followee_id),
  CHECK (follower_id <> followee_id)
);
CREATE INDEX follows_followee_idx ON follows (followee_id, created_at DESC);

CREATE TABLE blocks (
  blocker_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  blocked_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);
-- Reverse lookup: "who blocked me" is needed for the mutual block filter.
CREATE INDEX blocks_blocked_idx ON blocks (blocked_id, blocker_id);

CREATE TABLE mutes (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id        uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  target_user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  scope          text NOT NULL CHECK (scope IN ('posts', 'stories', 'all')),
  until          timestamptz,  -- NULL = indefinite; snooze = now() + 30 days
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, target_user_id, scope),
  CHECK (user_id <> target_user_id)
);

CREATE TABLE close_friends (
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  friend_id  uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE friend_lists (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name       text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 50),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, name)
);

CREATE TABLE friend_list_members (
  list_id    uuid NOT NULL REFERENCES friend_lists (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (list_id, user_id)
);

CREATE TABLE suggestion_dismissals (
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  dismissed_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, dismissed_id)
);

-- ---------------------------------------------------------------------------
-- 7.9 Groups and pages (before posts, which reference them)
-- ---------------------------------------------------------------------------

CREATE TABLE groups (
  id                     uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  name                   text NOT NULL CHECK (char_length(name) BETWEEN 3 AND 100),
  slug                   citext NOT NULL UNIQUE CHECK (slug::text ~ '^[a-z0-9-]{3,60}$'),
  description            text,
  privacy                text NOT NULL CHECK (privacy IN ('public', 'closed', 'secret')),
  rules_json             jsonb NOT NULL DEFAULT '[]'::jsonb,
  join_questions_json    jsonb NOT NULL DEFAULT '[]'::jsonb,
  cover_media_id         uuid REFERENCES media (id) ON DELETE SET NULL,
  city                   text,
  category               text,
  member_count           int NOT NULL DEFAULT 0 CHECK (member_count >= 0),
  created_by             uuid REFERENCES users (id) ON DELETE SET NULL,
  requires_post_approval boolean NOT NULL DEFAULT false,
  deletion_scheduled_at  timestamptz,
  deleted_at             timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX groups_name_trgm ON groups USING gin (search_normalize(name) gin_trgm_ops) WHERE deleted_at IS NULL AND privacy <> 'secret';

CREATE TABLE group_members (
  group_id    uuid NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role        text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'moderator', 'member')),
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'banned', 'muted')),
  status_until timestamptz,
  feed_enabled boolean NOT NULL DEFAULT true,
  joined_at   timestamptz NOT NULL DEFAULT now(),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX group_members_user_idx ON group_members (user_id) WHERE status = 'active';
-- Exactly one owner per group.
CREATE UNIQUE INDEX group_members_one_owner ON group_members (group_id) WHERE role = 'owner';

CREATE TABLE group_join_requests (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  group_id     uuid NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  answers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined', 'cancelled')),
  decided_by   uuid REFERENCES users (id) ON DELETE SET NULL,
  decided_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX group_join_requests_pending ON group_join_requests (group_id, user_id) WHERE status = 'pending';

CREATE TABLE pages (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  name            text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 100),
  slug            citext NOT NULL UNIQUE CHECK (slug::text ~ '^[a-z0-9-]{3,60}$'),
  category        text NOT NULL,
  description     text,
  avatar_media_id uuid REFERENCES media (id) ON DELETE SET NULL,
  cover_media_id  uuid REFERENCES media (id) ON DELETE SET NULL,
  follower_count  int NOT NULL DEFAULT 0 CHECK (follower_count >= 0),
  verified_at     timestamptz,
  deleted_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX pages_name_trgm ON pages USING gin (search_normalize(name) gin_trgm_ops) WHERE deleted_at IS NULL;

CREATE TABLE page_roles (
  page_id    uuid NOT NULL REFERENCES pages (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('admin', 'editor', 'analyst')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (page_id, user_id)
);

CREATE TABLE page_follows (
  page_id    uuid NOT NULL REFERENCES pages (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (page_id, user_id)
);
CREATE INDEX page_follows_user_idx ON page_follows (user_id);

-- ---------------------------------------------------------------------------
-- 7.3 Content
-- ---------------------------------------------------------------------------

CREATE TABLE link_previews (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  url_hash       bytea NOT NULL UNIQUE,
  url            text NOT NULL,
  title          text,
  description    text,
  image_media_id uuid REFERENCES media (id) ON DELETE SET NULL,
  site_name      text,
  fetched_at     timestamptz,
  status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ready', 'failed', 'blocked')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE posts (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  author_id           uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  group_id            uuid REFERENCES groups (id) ON DELETE CASCADE,
  page_id             uuid REFERENCES pages (id) ON DELETE CASCADE,
  body                text NOT NULL DEFAULT '' CHECK (char_length(body) <= 10000),
  body_html_sanitized text,
  audience            text NOT NULL CHECK (audience IN ('public', 'friends', 'close_friends', 'custom_list',
                                                        'specific_users', 'only_me', 'group_members')),
  audience_ref_id     uuid,  -- friend_lists.id for custom_list
  type                text NOT NULL CHECK (type IN ('text', 'media', 'link', 'poll', 'share')),
  shared_post_id      uuid REFERENCES posts (id) ON DELETE SET NULL,
  link_preview_id     uuid REFERENCES link_previews (id) ON DELETE SET NULL,
  location_text       text,
  approval_status     text NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('approved', 'pending', 'rejected')),
  moderation_state    text NOT NULL DEFAULT 'ok' CHECK (moderation_state IN ('ok', 'held', 'sensitive', 'removed')),
  content_hash        bytea,  -- duplicate-spam detection (11.11)
  comments_enabled    boolean NOT NULL DEFAULT true,
  reaction_count      int NOT NULL DEFAULT 0 CHECK (reaction_count >= 0),
  comment_count       int NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
  share_count         int NOT NULL DEFAULT 0 CHECK (share_count >= 0),
  search_tsv          tsvector GENERATED ALWAYS AS (
                        to_tsvector('russian', search_normalize(body)) || to_tsvector('english', search_normalize(body))
                      ) STORED,
  edited_at           timestamptz,
  deleted_at          timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CHECK (NOT (group_id IS NOT NULL AND page_id IS NOT NULL)),
  CHECK (audience <> 'group_members' OR group_id IS NOT NULL),
  CHECK ((audience = 'custom_list') = (audience_ref_id IS NOT NULL)),
  CHECK ((type = 'share') = (shared_post_id IS NOT NULL))
);
CREATE INDEX posts_author_idx ON posts (author_id, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX posts_group_idx ON posts (group_id, created_at DESC, id DESC) WHERE deleted_at IS NULL AND group_id IS NOT NULL;
CREATE INDEX posts_page_idx ON posts (page_id, created_at DESC, id DESC) WHERE deleted_at IS NULL AND page_id IS NOT NULL;
CREATE INDEX posts_search_idx ON posts USING gin (search_tsv) WHERE deleted_at IS NULL AND audience = 'public';
CREATE INDEX posts_content_hash_idx ON posts (content_hash, created_at DESC) WHERE content_hash IS NOT NULL;
CREATE INDEX posts_pending_approval_idx ON posts (group_id, created_at) WHERE approval_status = 'pending';

ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_pinned_fk FOREIGN KEY (pinned_post_id) REFERENCES posts (id) ON DELETE SET NULL;

CREATE TABLE post_media (
  post_id    uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  media_id   uuid NOT NULL REFERENCES media (id) ON DELETE CASCADE,
  position   smallint NOT NULL CHECK (position BETWEEN 0 AND 9),
  alt_text   text CHECK (char_length(alt_text) <= 1000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, media_id),
  UNIQUE (post_id, position)
);

CREATE TABLE post_audience_users (
  post_id    uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, user_id)
);
CREATE INDEX post_audience_users_user_idx ON post_audience_users (user_id);

CREATE TABLE post_edits (
  id            uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  post_id       uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  previous_body text NOT NULL,
  previous_audience text,
  edited_at     timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX post_edits_post_idx ON post_edits (post_id, edited_at DESC);

CREATE TABLE comments (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  post_id           uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  author_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  parent_comment_id uuid REFERENCES comments (id) ON DELETE CASCADE,
  root_comment_id   uuid REFERENCES comments (id) ON DELETE CASCADE,
  body              text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  media_id          uuid REFERENCES media (id) ON DELETE SET NULL,
  hidden_by_author  boolean NOT NULL DEFAULT false,
  reaction_count    int NOT NULL DEFAULT 0 CHECK (reaction_count >= 0),
  reply_count       int NOT NULL DEFAULT 0 CHECK (reply_count >= 0),
  edited_at         timestamptz,
  deleted_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  -- Depth 2: a reply always points at a root; replies-to-replies attach to the same root.
  CHECK ((parent_comment_id IS NULL) = (root_comment_id IS NULL))
);
CREATE INDEX comments_post_idx ON comments (post_id, created_at, id) WHERE root_comment_id IS NULL AND deleted_at IS NULL;
CREATE INDEX comments_root_idx ON comments (root_comment_id, created_at, id) WHERE deleted_at IS NULL;
CREATE INDEX comments_author_idx ON comments (author_id, created_at DESC);

CREATE TABLE reactions (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  target_type text NOT NULL CHECK (target_type IN ('post', 'comment', 'message', 'story')),
  target_id   uuid NOT NULL,
  kind        text NOT NULL CHECK (kind IN ('like', 'love', 'laugh', 'wow', 'sad', 'angry')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, target_type, target_id)
);
CREATE INDEX reactions_target_idx ON reactions (target_type, target_id, kind, created_at DESC);

CREATE TABLE mentions (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  source_type       text NOT NULL CHECK (source_type IN ('post', 'comment')),
  source_id         uuid NOT NULL,
  mentioned_user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_type, source_id, mentioned_user_id)
);
CREATE INDEX mentions_user_idx ON mentions (mentioned_user_id, created_at DESC);

CREATE TABLE hashtags (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  tag        citext NOT NULL UNIQUE CHECK (char_length(tag) BETWEEN 1 AND 100),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX hashtags_tag_trgm ON hashtags USING gin ((tag::text) gin_trgm_ops);

CREATE TABLE post_hashtags (
  post_id    uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  hashtag_id uuid NOT NULL REFERENCES hashtags (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, hashtag_id)
);
CREATE INDEX post_hashtags_tag_idx ON post_hashtags (hashtag_id, created_at DESC);

CREATE TABLE bookmark_collections (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name       text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 60),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, name)
);

CREATE TABLE bookmarks (
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  post_id       uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  collection_id uuid REFERENCES bookmark_collections (id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);
CREATE INDEX bookmarks_user_idx ON bookmarks (user_id, created_at DESC);

CREATE TABLE polls (
  id                 uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  post_id            uuid NOT NULL UNIQUE REFERENCES posts (id) ON DELETE CASCADE,
  multiple_choice    boolean NOT NULL DEFAULT false,
  results_visibility text NOT NULL DEFAULT 'after_vote' CHECK (results_visibility IN ('always', 'after_vote', 'after_close')),
  voters_visible     boolean NOT NULL DEFAULT false,
  closes_at          timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE poll_options (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  poll_id    uuid NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
  position   smallint NOT NULL CHECK (position BETWEEN 0 AND 9),
  label      text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 100),
  vote_count int NOT NULL DEFAULT 0 CHECK (vote_count >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (poll_id, position)
);

CREATE TABLE poll_votes (
  poll_id    uuid NOT NULL REFERENCES polls (id) ON DELETE CASCADE,
  option_id  uuid NOT NULL REFERENCES poll_options (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (poll_id, option_id, user_id)
);
CREATE INDEX poll_votes_user_idx ON poll_votes (user_id, poll_id);

-- ---------------------------------------------------------------------------
-- 7.4 Feed
-- ---------------------------------------------------------------------------

CREATE TABLE feed_entries (
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  post_id    uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  author_id  uuid NOT NULL,
  score      real NOT NULL DEFAULT 0,
  reason     text NOT NULL CHECK (reason IN ('friend', 'follow', 'group', 'page')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);
CREATE INDEX feed_entries_chrono_idx ON feed_entries (user_id, created_at DESC, post_id DESC);
CREATE INDEX feed_entries_post_idx ON feed_entries (post_id);  -- unfanout on delete

CREATE TABLE feed_state (
  user_id           uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  last_seen_post_id uuid,
  last_refreshed_at timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE hidden_posts (
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  post_id    uuid NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  reason     text NOT NULL CHECK (reason IN ('not_interested', 'hide', 'see_less', 'snooze_author')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

-- ---------------------------------------------------------------------------
-- 7.5 Stories
-- ---------------------------------------------------------------------------

CREATE TABLE stories (
  id                uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  author_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  page_id           uuid REFERENCES pages (id) ON DELETE CASCADE,
  media_id          uuid REFERENCES media (id) ON DELETE SET NULL,
  text_overlay_json jsonb,
  audience          text NOT NULL CHECK (audience IN ('public', 'friends', 'close_friends')),
  expires_at        timestamptz NOT NULL,
  archived          boolean NOT NULL DEFAULT false,
  deleted_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CHECK (media_id IS NOT NULL OR text_overlay_json IS NOT NULL),
  CHECK (expires_at <= created_at + interval '24 hours')
);
CREATE INDEX stories_author_active_idx ON stories (author_id, expires_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX stories_expiry_idx ON stories (expires_at) WHERE deleted_at IS NULL;

CREATE TABLE story_views (
  story_id   uuid NOT NULL REFERENCES stories (id) ON DELETE CASCADE,
  viewer_id  uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  viewed_at  timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (story_id, viewer_id)
);
CREATE INDEX story_views_viewer_idx ON story_views (viewer_id, viewed_at DESC);

-- Story reactions live in `reactions` (target_type = 'story'); 7.5 story_reactions folded in.

-- ---------------------------------------------------------------------------
-- 7.7 Chat
-- ---------------------------------------------------------------------------

CREATE TABLE conversations (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  type            text NOT NULL CHECK (type IN ('direct', 'group')),
  title           text CHECK (char_length(title) <= 100),
  avatar_media_id uuid REFERENCES media (id) ON DELETE SET NULL,
  created_by      uuid REFERENCES users (id) ON DELETE SET NULL,
  last_message_id uuid,
  last_message_at timestamptz,
  -- "<smaller uuid>:<larger uuid>" for direct chats; guarantees one chat per pair.
  direct_key      text UNIQUE,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CHECK ((type = 'direct') = (direct_key IS NOT NULL))
);

CREATE TABLE conversation_members (
  conversation_id      uuid NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  user_id              uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role                 text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),
  -- Message requests (14.1): non-friend DMs stay 'request' until accepted.
  state                text NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'request', 'declined')),
  joined_at            timestamptz NOT NULL DEFAULT now(),
  left_at              timestamptz,
  last_read_message_id uuid,
  muted_until          timestamptz,
  pinned               boolean NOT NULL DEFAULT false,
  archived             boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX conversation_members_user_idx ON conversation_members (user_id, archived) WHERE left_at IS NULL;

CREATE TABLE messages (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  conversation_id     uuid NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  sender_id           uuid REFERENCES users (id) ON DELETE SET NULL,
  client_message_id   uuid NOT NULL,
  type                text NOT NULL CHECK (type IN ('text', 'image', 'video', 'voice', 'file', 'sticker', 'system')),
  body                text CHECK (char_length(body) <= 10000),
  media_id            uuid REFERENCES media (id) ON DELETE SET NULL,
  reply_to_message_id uuid REFERENCES messages (id) ON DELETE SET NULL,
  edited_at           timestamptz,
  deleted_for_all_at  timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sender_id, client_message_id)  -- idempotent send
);
CREATE INDEX messages_conversation_idx ON messages (conversation_id, id DESC);

ALTER TABLE conversations ADD CONSTRAINT conversations_last_message_fk
  FOREIGN KEY (last_message_id) REFERENCES messages (id) ON DELETE SET NULL;

CREATE TABLE message_receipts (
  message_id   uuid NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  delivered_at timestamptz,
  read_at      timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, user_id)
);

CREATE TABLE message_deletions (
  message_id uuid NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (message_id, user_id)
);

-- ---------------------------------------------------------------------------
-- 7.8 Notifications
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type        text NOT NULL,
  actor_ids   uuid[] NOT NULL DEFAULT '{}',
  target_type text,
  target_id   uuid,
  group_key   text NOT NULL,  -- (type, target) grouping window key
  source_event_id uuid,       -- outbox event id; idempotency
  data_json   jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at     timestamptz,
  seen_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, source_event_id)
);
CREATE INDEX notifications_user_idx ON notifications (user_id, created_at DESC, id DESC);
CREATE INDEX notifications_unread_idx ON notifications (user_id) WHERE read_at IS NULL;
CREATE INDEX notifications_group_idx ON notifications (user_id, group_key, created_at DESC);

CREATE TABLE push_subscriptions (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  endpoint        text NOT NULL UNIQUE,
  p256dh          text NOT NULL,
  auth            text NOT NULL,
  user_agent      text,
  last_success_at timestamptz,
  failed_count    int NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX push_subscriptions_user_idx ON push_subscriptions (user_id);

CREATE TABLE email_digests (
  user_id      uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  frequency    text NOT NULL DEFAULT 'off' CHECK (frequency IN ('off', 'daily', 'weekly')),
  last_sent_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 7.9 Events
-- ---------------------------------------------------------------------------

CREATE TABLE events (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  host_type      text NOT NULL CHECK (host_type IN ('user', 'group', 'page')),
  host_id        uuid NOT NULL,
  created_by     uuid REFERENCES users (id) ON DELETE SET NULL,
  title          text NOT NULL CHECK (char_length(title) BETWEEN 3 AND 140),
  description    text,
  starts_at      timestamptz NOT NULL,
  ends_at        timestamptz,
  timezone       text NOT NULL DEFAULT 'Europe/Moscow',
  location_text  text,
  online_url     text,
  cover_media_id uuid REFERENCES media (id) ON DELETE SET NULL,
  privacy        text NOT NULL CHECK (privacy IN ('public', 'friends', 'group_members', 'invite_only')),
  capacity       int CHECK (capacity > 0),
  cancelled_at   timestamptz,
  deleted_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at IS NULL OR ends_at > starts_at)
);
CREATE INDEX events_host_idx ON events (host_type, host_id, starts_at);
CREATE INDEX events_upcoming_idx ON events (starts_at) WHERE deleted_at IS NULL AND cancelled_at IS NULL;

CREATE TABLE event_rsvps (
  event_id   uuid NOT NULL REFERENCES events (id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status     text NOT NULL CHECK (status IN ('going', 'interested', 'declined', 'invited')),
  invited_by uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (event_id, user_id)
);
CREATE INDEX event_rsvps_user_idx ON event_rsvps (user_id, status);

-- ---------------------------------------------------------------------------
-- 7.10 Moderation and admin
-- ---------------------------------------------------------------------------

CREATE TABLE reports (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  reporter_id     uuid REFERENCES users (id) ON DELETE SET NULL,
  target_type     text NOT NULL CHECK (target_type IN ('post', 'comment', 'user', 'group', 'page', 'message', 'story', 'event')),
  target_id       uuid NOT NULL,
  reason_code     text NOT NULL CHECK (reason_code IN ('spam', 'harassment', 'hate', 'violence', 'nudity', 'self_harm',
                                                       'scam', 'illegal', 'ip', 'impersonation', 'child_safety', 'other')),
  details         text CHECK (char_length(details) <= 2000),
  status          text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_review', 'actioned', 'dismissed')),
  priority        smallint NOT NULL DEFAULT 3 CHECK (priority BETWEEN 0 AND 3),  -- 0 = urgent
  assigned_to     uuid REFERENCES users (id) ON DELETE SET NULL,
  resolved_at     timestamptz,
  resolution_note text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX reports_queue_idx ON reports (priority, created_at) WHERE status IN ('open', 'in_review');
CREATE INDEX reports_target_idx ON reports (target_type, target_id);
CREATE INDEX reports_reporter_idx ON reports (reporter_id, created_at DESC);

CREATE TABLE moderation_actions (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  moderator_id   uuid REFERENCES users (id) ON DELETE SET NULL,
  report_id      uuid REFERENCES reports (id) ON DELETE SET NULL,
  target_user_id uuid REFERENCES users (id) ON DELETE SET NULL,
  target_type    text NOT NULL,
  target_id      uuid NOT NULL,
  action         text NOT NULL CHECK (action IN ('remove_content', 'warn', 'mute', 'suspend', 'ban', 'restore',
                                                 'mark_sensitive', 'shadow_hold', 'dismiss', 'escalate')),
  reason         text NOT NULL,
  policy_ref     text,
  expires_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX moderation_actions_user_idx ON moderation_actions (target_user_id, created_at DESC);

CREATE TABLE appeals (
  id                   uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  moderation_action_id uuid NOT NULL REFERENCES moderation_actions (id) ON DELETE CASCADE,
  user_id              uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  body                 text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  status               text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'upheld', 'overturned')),
  reviewed_by          uuid REFERENCES users (id) ON DELETE SET NULL,
  reviewed_at          timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (moderation_action_id, user_id)
);

-- Append-only: the app role has INSERT/SELECT only (see docs/database.md, roles).
CREATE TABLE audit_log (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  actor_id    uuid,
  action      text NOT NULL,
  entity_type text NOT NULL,
  entity_id   uuid,
  before_json jsonb,
  after_json  jsonb,
  justification text,
  ip_hash     bytea,
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_id, created_at DESC);

CREATE OR REPLACE FUNCTION audit_log_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only';
END $$;
CREATE TRIGGER audit_log_no_update BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();

CREATE TABLE banned_terms (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  term       text NOT NULL,
  match_type text NOT NULL CHECK (match_type IN ('exact', 'substring', 'regex')),
  severity   smallint NOT NULL CHECK (severity BETWEEN 1 AND 3),
  action     text NOT NULL CHECK (action IN ('block', 'flag', 'shadow_hold')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (term, match_type)
);

CREATE TABLE blocked_domains (
  domain     citext PRIMARY KEY,
  reason     text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE feature_flags (
  key             text PRIMARY KEY CHECK (key ~ '^[a-z0-9_.]+$'),
  enabled         boolean NOT NULL DEFAULT false,
  rollout_percent smallint NOT NULL DEFAULT 0 CHECK (rollout_percent BETWEEN 0 AND 100),
  rules_json      jsonb NOT NULL DEFAULT '{}'::jsonb,
  description     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE takedown_requests (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  source         text NOT NULL CHECK (source IN ('regulator', 'court', 'rightsholder', 'other')),
  reference      text,
  target_type    text NOT NULL,
  target_id      uuid,
  received_at    timestamptz NOT NULL,
  status         text NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'actioned', 'rejected')),
  handled_by     uuid REFERENCES users (id) ON DELETE SET NULL,
  handled_at     timestamptz,
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 7.11 Platform
-- ---------------------------------------------------------------------------

CREATE TABLE outbox (
  id             uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  aggregate_type text NOT NULL,
  aggregate_id   uuid NOT NULL,
  event_type     text NOT NULL,
  event_version  smallint NOT NULL DEFAULT 1,
  payload_json   jsonb NOT NULL,
  published_at   timestamptz,
  attempts       int NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX outbox_unpublished_idx ON outbox (id) WHERE published_at IS NULL;

CREATE TABLE idempotency_keys (
  key           text NOT NULL,
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  request_hash  bytea NOT NULL,
  response_status smallint,
  response_json jsonb,
  expires_at    timestamptz NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);
CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (expires_at);

CREATE TABLE data_export_jobs (
  id            uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status        text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'ready', 'failed', 'expired')),
  file_media_id uuid REFERENCES media (id) ON DELETE SET NULL,
  requested_at  timestamptz NOT NULL DEFAULT now(),
  completed_at  timestamptz,
  expires_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX data_export_jobs_user_idx ON data_export_jobs (user_id, requested_at DESC);

CREATE TABLE consents (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id    uuid REFERENCES users (id) ON DELETE CASCADE,
  anonymous_id uuid,  -- cookie consent before sign-up
  type       text NOT NULL CHECK (type IN ('terms', 'privacy', 'pd_processing', 'marketing', 'cookies_analytics')),
  version    text NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  ip_hash    bytea,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (user_id IS NOT NULL OR anonymous_id IS NOT NULL)
);
CREATE INDEX consents_user_idx ON consents (user_id, type, granted_at DESC);

CREATE TABLE recent_searches (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  query      text NOT NULL CHECK (char_length(query) <= 200),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX recent_searches_user_idx ON recent_searches (user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- updated_at triggers on every table that has the column
-- ---------------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOR t IN
    SELECT c.table_name FROM information_schema.columns c
    JOIN information_schema.tables tb ON tb.table_name = c.table_name AND tb.table_schema = c.table_schema
    WHERE c.table_schema = 'public' AND c.column_name = 'updated_at' AND tb.table_type = 'BASE TABLE'
      AND c.table_name <> 'audit_log'
  LOOP
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
                   t || '_set_updated_at', t);
  END LOOP;
END $$;

COMMIT;
